site_name: miraheze-bkr-cn-platform

site_description: Miraheze 后室中文站务平台

site_author: RainPurNova418

repo_url: https://github.com/RainPurNova418/miraheze-bkr-cn-platform
repo_name: GitHub

nav:
  - 首页: index.md

plugins:
  - search
