site_name: miraheze-bkr-cn-platform

site_description: Miraheze 后室中文站务平台

site_author: RainPurNova418

repo_url: https://github.com/RainPurNova418/miraheze-bkr-cn-platform
repo_name: GitHub

theme:
  name: material
  language: zh
  font:
    text: Noto Sans SC
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - 首页: index.md

plugins:
  - search
